### 1. Authenticate and get Bearer Token
POST https://api-sandbox.justgo.com/api/v2.2/Auth
Accept: */*
Content-Type: application/json

{
  "secret": "{{my_secret_value}}"
}

> {%
    // This script captures the token and saves it globally
    client.global.set("auth_token", response.body.data.accessToken);
%}

###

### 2. Find Member by Attributes
GET https://api-sandbox.justgo.com/api/v2.2/Members/FindByAttributes?LastName=Lorenc&FirstName=Swavek&ModifiedAfter=2025-04-04T13:48:32.000Z
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.global.set("id", response.body.data[0].id);
    client.global.set("memberId", response.body.data[0].memberNumber);
    client.log('id '+ response.body.data[0].id);
    client.log('memberId '+ response.body.data[0].memberNumber);
%}

###

### 3. Submit Competition Rankings
POST https://api-sandbox.justgo.com/api/v2.2/Competitions/Rankings
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "memberId": "{{id}}",
  "date": "2026-03-30T00:09:29.308Z",
  "type": "Rating"
}

### 2. Find All Members recently changed
GET https://api-sandbox.justgo.com/api/v2.2/Members/FindByAttributes?ModifiedAfter=2026-07-03T10:00:32.000Z
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.global.set("totalRecords", response.body.totalRecords);
    client.log('totalRecords '+ response.body.totalRecords);
%}
