export enum EventEntryCommand {
  NO_COMMAND = 'NO_COMMAND',
  ENTER = 'ENTER',
  ENTER_WAITING_LIST = 'ENTER_WAITING_LIST',
  DROP = 'DROP',
  DROP_WAITING_LIST = 'DROP_WAITING_LIST',
  REVERT_DROP = 'REVERT_DROP',
  CONFIRM = 'CONFIRM'
}
